apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kponevaphone/conf.git
    targetRevision: test 
    path: app
  destination: 
    server: https://kubernetes.default.svc
    namespace: hello

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true