apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    # value: https://github.com/google/docsy-example.git
    value: git@github.com:kponevaphone/conf.git
  - name: image-reference
    # value: container.registry.com/sublocation/my_app:version 
    value: devubu:5000/test:latest 
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: $(workspaces.source.path)/doc/Dockerfile